ALTER PROCEDURE LISTA_EMPLEADOS
	@IDESTADOCIVIL INT,
	@SEXO CHAR(1),
	@NOMBRE VARCHAR(100)
AS
BEGIN
	SELECT 
CONCAT(NUMRUN_EMP,'-',DVRUN_EMP) AS 'RUN',
CONCAT(PNOMBRE_EMP,' ',SNOMBRE_EMP,' ',
APPATERNO_EMP,' ',APMATERNO_EMP) AS 'NOMBRE COMPLETO',
DIRECCION_EMP AS DIRECCION,
CELULAR_EMP AS CELULAR,
CONCAT('NACIO EL AÑO: ',YEAR(FECHA_NAC)) AS 'AÑO NACIMIENTO',
CONCAT('ESTE AÑO CUMPLE: ', DATEDIFF(YEAR,FECHA_NAC,GETDATE())) AS 'EDAD',
CONCAT('EL PRIMER DIGITO DE SU CELULAR ES: ',LEFT(CELULAR_EMP,1)) AS 'PRIMERO DIGITO CELULAR',
CONCAT('SU NOMBRE TIENE ', LEN(PNOMBRE_EMP) ,' CARACTERES') AS 'NUM CARACRTERES NOMBRE',
UPPER(NOMBRE_COMUNA) AS 'NOMBRE COMUNA',
UPPER(TS.DESCRIPCION) AS 'TIPO SALUD',
UPPER(EC.NOMBRE_ESTADO_CIVIL) AS 'ESTADP CIVIL',
SUELDO_BASE AS 'SUELDO BASE',
SUELDO_BASE *0.15 AS 'VACACIONES',
SUELDO_BASE *0.25 AS 'NAVIDAD',
SUELDO_BASE *0.2 AS 'TRIMESTRAL',
TS.PCT_SUELDO AS '% SOBRE SUELDO',
--CONVERT(FLOAT,TS.PCT_SUELDO)/100,
SUELDO_BASE * CONVERT(FLOAT,TS.PCT_SUELDO)/100 AS 'MONTO A PAGAR POR TIPO SALUD'
INTO TABLA_@NOMBRE
FROM EMPLEADO AS EMP
INNER JOIN COMUNA AS C
ON EMP.ID_COMUNA = C.ID_COMUNA
INNER JOIN TIPO_SALUD AS TS
ON EMP.ID_TIPO_SAL = TS.ID_TIPO_SAL
INNER JOIN ESTADO_CIVIL AS EC
ON EMP.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL
WHERE EMP.ID_ESTADO_CIVIL =@IDESTADOCIVIL
AND EMP.SEXO = @SEXO;

SELECT * FROM TABLA_@NOMBRE; 

END

EXEC LISTA_EMPLEADOS 1,'M','MASCULINOS_CASADOS'